TYPE = (
	
	('SOPA' , 'SOPA') ,
	('PRINCIPIO' , 'PRINCIPIO'),
	('CARNE' , 'CARNE'),
	('ENSALADA' , 'ENSALADA'),
	('ARROZ' , 'ARROZ'),
	('BEBIDA' , 'BEBIDA') ,
	('ADICIONAL' , 'ADICIONAL' ) ,
	('PRINCIPAL' , 'PRINCIPAL'),
	('ACOMPANANTE' , 'ACOMPANANTE')

)

SECTION = (

	('DESAYUNO' , 'DESAYUNO'),
	('ALMUERZO' , 'ALMUERZO') ,
	('ADICIONAL' , 'ADICIONAL')



	)